#!/bin/bash

set -e

cd /srv/gitlab

touch /var/log/gitlab/geo.log

echo "Starting geo_log_cursor"
/srv/gitlab/ee/bin/geo_log_cursor ${GEO_LOGCURSOR_ARGUMENTS} 2&1 > /var/log/gitlab/geo_stdout.log &

tail -f /var/log/gitlab/*

wait
