#!/bin/bash

set -e

cd /srv/gitlab

debug=''
if [ "${DEBUG}x" -ne "x"]; then
  debug='--debug'
fi

echo "Starting geo_log_cursor"
/srv/gitlab/ee/bin/geo_log_cursor ${debug} >> /var/log/gitlab/geo_log_cursor.log 2>&1

wait
