#!/bin/bash

set -e

cd /srv/gitlab

LOGFILE=/var/log/gitlab/geo_log_cursor.log
touch $LOGFILE

debug=''
if [ "${DEBUG}x" != "x"]; then
  debug='--debug'
fi

echo "Starting geo_log_cursor"
/srv/gitlab/ee/bin/geo_log_cursor ${debug} >> $LOGFILE 2>&1

tail -f $LOGFILE

wait
