#!/bin/bash

set -e

touch /var/log/gitlab/workhorse.log

gitlab-workhorse -listenAddr 0.0.0.0:8181 -documentRoot "/home/git/gitlab/public" -secretPath "/home/git/gitlab/.gitlab_workhorse_secret" -config "/var/opt/gitlab/config/gitlab/workhorse-config.toml" >> /var/log/gitlab/workhorse.log 2>&1
