#!/usr/bin/env ruby

require 'erb'
require 'fileutils'

def compile_assets
  ENV['COMPILE_ASSETS'].eql?('true')
end

puts "Rendering Dockerfile"

template = ERB.new(File.read('Dockerfile.erb'))
File.write('Dockerfile', template.result)
