#!/bin/bash

set -e

echo "Starting workhorse"
/scripts/start-workhorse &

echo "Starting unicorn"
/home/git/gitlab/bin/bundle exec unicorn -E production -c /home/git/gitlab/config/unicorn.rb /home/git/gitlab/config.ru &

tail -f /var/log/gitlab/*

wait
