#!/bin/bash

set -e

echo "Starting workhorse"
/scripts/start-workhorse &

# Workaround for disablign the authorized_keys write to the database.
# A proper fix is being tracked in: https://gitlab.com/charts/helm.gitlab.io/issues/89
/home/git/gitlab/bin/rails runner -e production 'include Gitlab::CurrentSettings; current_application_settings.update_attribute(:authorized_keys_enabled, false)' &

echo "Starting unicorn"
/home/git/gitlab/bin/bundle exec unicorn -E production -c /home/git/gitlab/config/unicorn.rb /home/git/gitlab/config.ru &

tail -f /var/log/gitlab/*

wait
