#!/bin/bash

set -e

echo "Generating Host Keys"

ssh-keygen -A

echo "Starting OpenSSH"
touch /var/log/gitlab-shell/ssh.log
/usr/sbin/sshd -E /var/log/gitlab-shell/ssh.log &

echo "Tailing Logs"
tail -f /var/log/gitlab-shell/*

wait
