#!/usr/bin/env ruby

require 'object_storage_backup'

abort("uploads_tar_path needs to be passed as an argument to the script") unless ARGV.length

remote_bucket_name = ENV['BUCKET_NAME'] || 'gitlab-uploads'
ObjectStorageBackup.new('uploads', ARGV[0], remote_bucket_name).restore
