#!/bin/bash



set -e

touch /var/log/gitlab/workhorse.log

gitlab-workhorse \
  ${GITLAB_WORKHORSE_EXTRA_ARGS} \
  -listenAddr 0.0.0.0:${GITLAB_WORKHORSE_LISTEN_PORT:-8181} \
  -documentRoot "/srv/gitlab/public" \
  -secretPath "/etc/gitlab/gitlab-workhorse/secret" \
  -config "/srv/gitlab/config/workhorse-config.toml" \
>> /var/log/gitlab/workhorse.log 2>&1 &

tail -f /var/log/gitlab/workhorse.log

wait
