#!/bin/bash

set -e

mkdir -p /var/log/gitlab
touch /var/log/gitlab/workhorse.log

exec gitlab-workhorse \
  ${GITLAB_WORKHORSE_EXTRA_ARGS} \
  -listenAddr 0.0.0.0:8181 \
  -documentRoot "/srv/gitlab/public" \
  -secretPath "/srv/gitlab/.gitlab_workhorse_secret" \
  -config "/var/opt/gitlab/config/gitlab/workhorse-config.toml" \
>> /var/log/gitlab/workhorse.log 2>&1
