#!/bin/bash

set -e

echo "Starting Sidekiq"
/home/git/gitlab/bin/bundle exec sidekiq \
              -r /home/git/gitlab \
              -e production \
              -c $SIDEKIQ_CONCURRENCY \
              -t $SIDEKIQ_TIMEOUT \
              -C /home/git/gitlab/config/sidekiq_queues.yml &

tail -f /var/log/gitlab/*

wait
