#!/bin/bash

set -e

echo "Starting Sidekiq"
/srv/gitlab/bin/bundle exec sidekiq \
              -r /srv/gitlab \
              -e production \
              -c $SIDEKIQ_CONCURRENCY \
              -t $SIDEKIQ_TIMEOUT \
              -C /srv/gitlab/config/sidekiq_queues.yml &

tail -f /var/log/gitlab/*

wait
