#!/bin/bash

set -e

# Workaround for disabling the authorized_keys write to the database.
# A proper fix is being tracked in: https://gitlab.com/gitlab-org/gitlab-ee/issues/4156
read -r -d '\0' DISABLE_AUTHORIZED_KEYS <<- EOM
# Newer GitLab versions use cached json rather than activerecord for the 'current' settings. Use the uncached.
if ::ApplicationSetting.respond_to?(:current_without_cache)
  current_settings = ::ApplicationSetting.current_without_cache
else
  current_settings = ::ApplicationSetting.current
end

(current_settings || ::ApplicationSetting.create_from_defaults).update_attribute(:authorized_keys_enabled, false)
\0
EOM

/srv/gitlab/bin/rails runner -e production "$DISABLE_AUTHORIZED_KEYS"
