#!/bin/bash

set -e

echo "Checking Geo database migrations are up-to-date"

UPGRADE_STATUS_DIR="${UPGRADE_STATUS_DIR:-/tmp/gitlab-upgrade}"
GITLAB_REVISION=$(cat /srv/gitlab/REVISION)
CONNECTION_DIGEST=$(md5sum /srv/gitlab/config/database_geo.yml | awk '{ print $1 }' )
MIGRATE_STATUS_FILE="${UPGRADE_STATUS_DIR}/db-migrate-${CONNECTION_DIGEST}-${GITLAB_REVISION}"

# Exit if the database has already been updated
if [ -f "${MIGRATE_STATUS_FILE}" ] && ( grep -qFx 0 "${MIGRATE_STATUS_FILE}" ); then
  echo "Geo database migrations have already been run"
  exit 0
fi

# Seed or migrate the database
echo "Checking for new migrations"
mkdir -p "${UPGRADE_STATUS_DIR}"
umask 077
cd /srv/gitlab

/srv/gitlab/bin/rake geo:db:migrate && STATUS=$? || STATUS=$?


# Update the status
echo "Storing Migration Status"
echo $STATUS > "${MIGRATE_STATUS_FILE}"
exit $STATUS
